### ISSUE TITLE
Otestovani aplikace

### ISSUE THREAD

**Issue by GeorgeFreelanceDeveloper** [LucyQuantAnalyst/cafe-management-system#3]
Prosim pridat integracni testy do be casti aplikace na:

* Controllery
* Services
* Repositories

Poznamka: Zprovoznit si h2 base inmemory databazi pro integracni testy.

Vetev: feature/add-integration-tests

**Comment by LucyFreelanceDeveloper** [comment]
Testy pro Repositories jsou pridany @GeorgeFreelanceDeveloper prosim o kontrolu a na testech pro Controllery prave pracuji.
